spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: info
    com.example.supportdesk: info
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn